### ISSUE TITLE
new Ip's to block, not in your list

### ISSUE THREAD

**Issue by stofftreiber** [ignaciocastro/a-dove-is-dumb#16]
CONNECT 9k046300lp.adobe.io:443 HTTP/1.1
Host: 9k046300lp.adobe.io:443

CONNECT s.go-mpulse.net:443 HTTP/1.1
Host: s.go-mpulse.net:443
(connecting w/ acro....)

so we have new:
127.0.0.1 9k046300lp.adobe.io
127.0.0.1 s.go-mpulse.net (?)

cheers

**Comment by ignaciocastro** [comment]
9k046300lp.adobe.io **✅ Done,** thank you for your countribution!
s.go-mpulse.net is out of scope for this repository.
