### ISSUE TITLE
Photoshop 2024 25.6  crashes

### ISSUE THREAD

**Issue by Potato-007** [ignaciocastro/a-dove-is-dumb#17]
...if I add this list to hosts file on macOS. I had no time to examine exactly which entry is responsible.

**Comment by ignaciocastro** [comment]
Hi @Potato-007. Next time you're free, could you check, one by one, if commenting (removing) either of these lines from your hosts file stops the crashes?

```
0.0.0.0 cc-api-data.adobe.io
0.0.0.0 cc-api-data-stage.adobe.io
0.0.0.0 prod.adobegenuine.com
0.0.0.0 gocart-web-prod-ue1-alb-1461435473.us-east-1.elb.amazonaws.com
0.0.0.0 fp.adobestats.io
```

Your input is very appreciated, since I don't have a macOS machine available to test. Thank you

**Comment by ignaciocastro** [comment]
No reply from author hence no possibility for me to try and fix it. Closed
