### ISSUE TITLE
new domain, not on your list yet

### ISSUE THREAD

**Issue by MikuDroid** [ignaciocastro/a-dove-is-dumb#18]
0qnxjg7wfg.adobestats.io
please add, thank you.

**Comment by MikuDroid** [comment]
seems like the contents inside the request is encrypted, so i don't know how to filter the request using your provided filter (/integritychecker/machineevents/v1). I managed to find this domain 1 by 1 using charles. Is there an easy way to filter future hosts?

![image](https://github.com/user-attachments/assets/70f18371-0fb0-4156-b923-513a5e69e50e)

**Comment by ignaciocastro** [comment]
You need to enable HTTPS decryption to be able to search correctly. Thanks for your contribution!
