### ISSUE TITLE
The hosts file seems invalid

### ISSUE THREAD

**Issue by idesign2018** [ignaciocastro/a-dove-is-dumb#2]
After I added [winhosts](https://a.dove.isdumb.one/winhosts.txt) to hosts, I still got a message "telemetry replace" when I restarted Photoshop. I also disabled Photoshop from connecting to the Internet, but there was still a telemetry prompt. When I turned off the VPN, it could be used normally without the telemetry prompt. But I need to use VPN for work and cannot turn off the VPN program. Is there any other way?

As shown below:
![image](https://github.com/ignaciocastro/a-dove-is-dumb/assets/42263070/12b5e689-995c-4f62-acf8-b1248b6b69d6)

**Comment by ignaciocastro** [comment]
@idesign2018 This /should/ be out of scope, but if you're using Clash, please consider using [this format instead](https://github.com/cmliu/ACL4SSR/blob/main/Clash/adobe.list). If it works do tell me and I'll add it as an option.

**Comment by idesign2018** [comment]
> @idesign2018 This /should/ be out of scope, but if you're using Clash, please consider using [this format instead](https://github.com/cmliu/ACL4SSR/blob/main/Clash/adobe.list). If it works do tell me and I'll add it as an option. 这/应该/超出范围，但如果您使用 Clash，请考虑改用此格式。如果它有效，请告诉我，我会将其添加为选项。

OK, thanks. I'm using Clash. I'll try it out tonight. Hope it works.

**Comment by idesign2018** [comment]
> @idesign2018 This /should/ be out of scope, but if you're using Clash, please consider using [this format instead](https://github.com/cmliu/ACL4SSR/blob/main/Clash/adobe.list). If it works do tell me and I'll add it as an option.这/应该/超出范围，但如果您使用 Clash，请考虑改用此格式。如果它有效，请告诉我，我会将其添加为选项。

Photoshop 2024 seems to have been resolved, but Illustrator 2024 will still appear, as shown below:
![image](https://github.com/ignaciocastro/a-dove-is-dumb/assets/42263070/c80db7fa-b35c-4fa1-bf78-b3cb10ef12e0)

I copied the contents of [adobe.list](https://github.com/cmliu/ACL4SSR/blob/main/Clash/adobe.list) to the `hosts` file and saved it, and restarted Illustrator 2024, but it still cannot be used. I don't know if my operation is correct

My firewall settings
**Outbound rules:**
![image](https://github.com/ignaciocastro/a-dove-is-dumb/assets/42263070/034cb818-dabd-414a-b6c0-b055fee3f75c)

**Inbound rules:**
![image](https://github.com/ignaciocastro/a-dove-is-dumb/assets/42263070/325139f0-7eb5-427d-980a-dda7c0ff9b80)

For Photoshop, I don't know if the firewall is at work.

**Comment by scottial77** [comment]
Use Fiddler Classic to check domains. I've found this:

o1383653.ingest.sentry.io

**Comment by idesign2018** [comment]
> Use Fiddler Classic to check domains. I've found this:使用 Fiddler Classic 检查域。我发现了这个：
> 
> o1383653.ingest.sentry.io

Do I need to add it to hosts?

**Comment by scottial77** [comment]
I think yes, because is used by Lightroom Classic

Il Gio 27 Giu 2024, 14:15 Aidesign ***@***.***> ha scritto:

**Comment by ignaciocastro** [comment]
sentry.io domains are not in the scope of this repository and if you're seeing it, it means Adobe Genuine Service is running in your PC. Fix that first, can't and will not go further
