### ISSUE TITLE
New domain report

### ISSUE THREAD

**Issue by Spike141281** [ignaciocastro/a-dove-is-dumb#21]
POST https://vgetwxoqno.adobe.io/integritychecker/machineevents/v1 HTTP/1.1
Host: vgetwxoqno.adobe.io
Connection: keep-alive
Content-Length: 527
Content-Type: application/json
X-Request-Id: 4
x-api-key: ic-prod
Accept-Language: en-US,en;q=0.9
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) AcrobatServices/24.3.20112 Chrome/105.0.0.0 Safari/537.36
Origin: https://vgetwxoqno.adobe.io
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br

**Comment by ignaciocastro** [comment]
**✅ Done**, Thank you for your contribution!
