### ISSUE TITLE
[Question] How to report new domain?

### ISSUE THREAD

**Issue by sukmaraga** [ignaciocastro/a-dove-is-dumb#31]
1. macOS user here, how to report new domain from macos system? 
2. how to tell if blocking is working. is can't access adobe websites is a way to tell blocking is working?

**Comment by ignaciocastro** [comment]
1. HTTP Toolkit, Wireshark, Charles Proxy
2. Enter _ic.adobe.io_ from your browser. If you see 404 Not Found, you're not blocking correctly. If you get a browser error (ERR_ADDRESS_INVALID) you're blocking correctly.
