### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by gingerbeardman** [ignaciocastro/a-dove-is-dumb#6]
It would be good to package update as release, so we can be notified through github notifications system.

releases would also enable software to install these more automatically.

**Comment by ignaciocastro** [comment]
**❌Not planned** SwitchHosts and Hostsman can be used to receive updates automatically. Github is not being used as a provider but as an info hoster, hence the reason it's raw files are never linked and CDN links are prefered. For updates you can subscribe to the Telegram channel instead.

**Comment by gingerbeardman** [comment]
OK no worries!
