### ISSUE TITLE
RPZ & UNBOUND FORMAT

### ISSUE THREAD

**Issue by alsyundawy** [ignaciocastro/a-dove-is-dumb#7]
Please support rpz and unbound format

**RPZ Format**

```
$TTL 300
@ SOA localhost. root.localhost. 1715037180 43200 3600 259200 300
  NS  localhost.

domain.tld CNAME .
*.domain.tld CNAME .
```

**Unbound Format**

```
server:
local-zone: "domain.tld." always_nxdomain
```

**Comment by ignaciocastro** [comment]
**❌ Out of scope** Apart from Pi-hole every format is directed to singular users in their personal PCs instead of hostmasters. If you need to use BIND9 then you can block any subdomain of adobestats.io instead.

**Comment by alsyundawy** [comment]
its for unbound & bind9 dns recursive server
