### ISSUE TITLE
rule-providers format for Clash

### ISSUE THREAD

**Issue by People-11** [ignaciocastro/a-dove-is-dumb#9]
Nowadays, there are two commonly used rule formats: rules and rule-providers.
Simply put, rules is traditional method while rule-providers is more convenient and modern, it allows users to add the latest rules with one click without copying and pasting.
However, the current clash.txt format only works with rules.
I would wish to add a clash.yaml adapted to rule-providers, in a format similar to the following:

```
payload:
  - DOMAIN,ic.adobe.io
  - DOMAIN,cc-api-data.adobe.io
  - DOMAIN,cc-api-data-stage.adobe.io
  - DOMAIN,prod.adobegenuine.com
```

**Comment by ignaciocastro** [comment]
Hello @People-11, sorry for taking so long thank you for your insight on how Clash works. This is really appreciated since I have no access to it.
I have two questions, and I'd appreciate if you could help me with them:
1) Is that example you showed enough to be adapted into clash.yaml or would I need to add anything else to close it?
2) It'd be better to add those domains and then add a wildcard for adobestats.io subdomains. How would that be added? Would `DOMAIN,*.adobestats.io` be enough?

Thank you!

**Comment by People-11** [comment]
> Hello @People-11, sorry for taking so long thank you for your insight on how Clash works. This is really appreciated since I have no access to it. I have two questions, and I'd appreciate if you could help me with them:
> 
> 1. Is that example you showed enough to be adapted into clash.yaml or would I need to add anything else to close it?
> 2. It'd be better to add those domains and then add a wildcard for adobestats.io subdomains. How would that be added? Would `DOMAIN,*.adobestats.io` be enough?
> 
> Thank you!

I've made one in my repo https://github.com/People-11/Adobe-Block-Rule/blob/main/clash.yaml , clash users just need to add this link into rule-providers set to use it.

Yes you can block all domain end with it like this
```
payload:
  - DOMAIN-SUFFIX,adobestats.io
  - DOMAIN-SUFFIX,adobe.io
```
 
 And you can block all domain with the keywork in it like this
```
payload:
 - DOMAIN-KEYWORD,adobestats
```
 
 But I'm not sure if Adobe will add useful stuff to xxxx.adobe.io rather than just telemetry, so I didn't do that in my repo.

**Comment by ignaciocastro** [comment]
Good morning @People-11. Could you check whether the new file [clash.yaml](https://a.dove.isdumb.one/clash.yaml) is correctly formatted? If so, we can close this as completed and I thank you for helping this project.

**Comment by People-11** [comment]
@ignaciocastro Congrats! The file you provided is working fine in Clash
![image](https://github.com/user-attachments/assets/bb866b41-2a5d-4fd9-8269-5f76a16115ec)
